# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ocean
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

exclude: [
  "src",
  "node_modules",
  "tasks",
  "gulp-config.json",
  "gulpfile.js",
  "package.json",
  "README.md",
  "Gemfile",
  "Gemfile.lock",
  ".babelrc",
  ".eslintrc.json",
  "server.js"
]

# Build settings
markdown: kramdown

prose:
  rooturl: '_releases'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  collections:
    - releases
  metadata:
    _releases:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
      - name: "soundcloud_url"
        field:
          label: "The full soundcloud url"
          element: "text"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""